### PR TITLE
`runCommitLikeCommand`: Open COMMIT_EDITMSG in the current workspace

### LINKED ISSUE #301: Multiple vscode windows, one git project: magit.commit opens in wrong window
I'm working on a sort-of monorepo where I have multiple projects open in separate vscode windows. The setup is roughly the following:

```
root/
├── .git/
├── subfolder1/
├── subfolder2/
└── special_subfolder/
```

Usually, two vscode instances are open: One for `root/` (to work on `root/` as well as `subfolder1/` and `subfolder2/`) and one for `special_subfolder/`. 

edamagit handles this fairly well: I can simultaneously use it in every window without major hiccups, with one issue:

When I run `magic.commit` in the vscode instance for `special_subfolder/`, `COMMIT_EDITMSG` is opened in the instance for `root/`, with everything else staying in the instance of `special_subfolder/`. I expect `COMMIT_EDITMSG` to open in the instance `magic.commit` is executed.

Is there a configuration option I missed, or is this an unusual use case that isn't covered (yet)? 

If you consider this a bug, would you accept a PR for a fix?

### PR DESCRIPTION
**Pull request by the-kenny**
Fixes #301

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks! Would be great to see this merged @kahole !

**Comment by kahole** [comment]
Is the first workspace element always the current?

**Comment by the-kenny** [comment]
The first is not necessarily the current one. I am pretty sure it's the one at the top in the 'Explorer' view when there are multiple workspaces open in the current window.

I *think* using `[0]` is okay as we just need a folder which is open in the current window.

**Comment by kahole** [comment]
I see 👍🏻 Will try to get it merged soon

**Pull request merged**
